services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ${VITE_DOCKERFILE}
    ports:
      - "${VITE_DEV_PORT}:5173"
      - "${VITE_PREVIEW_PORT}:4173"
      - "${NGINX_PORT}:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ${NODE_DOCKERFILE}
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
      - smtp

  database:
    container_name: database
    image: mongo:8.0.8
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data/database:/data/db

  smtp:
    container_name: smtp
    image: axllent/mailpit
    ports:
      # Mailpit SMTP port is 1025, no need to expose it
      - "${MAILPIT_PORT}:8025" # Mailpit web interface
    environment:
      MP_DATABASE: /data/smtp.db # Use persistent storage
    volumes:
      - ./data/smtp:/data
