services:
  frontend:
    image: ghcr.io/antoine-nve/ledge-frontend:${IMAGE_TAG:-latest}
    env_file:
      - path: frontend/.env
        required: true
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped

  backend:
    image: ghcr.io/antoine-nve/ledge-backend:${IMAGE_TAG:-latest}
    env_file:
      - path: backend/.env
        required: true
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - loki
    restart: unless-stopped

  mongo:
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped

  redis:
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  loki:
    image: grafana/loki:3.5
    volumes:
      - loki:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - loki
    restart: unless-stopped

  migrate:
    image: ghcr.io/antoine-nve/ledge-backend:latest
    env_file:
      - path: backend/.env
        required: true
    depends_on:
      - loki
    entrypoint: ["node", "dist/backend/scripts/migrate.js", "up"]

volumes:
  loki:
  grafana:
